version: '3.9'

services:
  clinic-frontend:
    image: node:lts
    working_dir: /clinic-frontend
    container_name: "Clinic-Frontend"
    volumes:
      - ./clinic-frontend:/clinic-frontend
    ports:
      - 8080:8080
    networks:
      - doctor-app-1
    depends_on:
      - backend
    command: >
      sh -c "npm i -g --force yarn && yarn install && yarn start"
  frontend:
    image: node:lts
    working_dir: /frontend
    container_name: "Frontend"
    volumes:
      - ./frontend:/frontend
    ports:
      - 8800:8000
    networks:
      - doctor-app-1
    depends_on:
      - backend
    command: >
      sh -c "npm i -g --force yarn && yarn install && yarn start"
      
  admin-frontend:
    image: node:lts
    working_dir: /frontend
    container_name: "Admin-Frontend"
    volumes:
      - ./frontend:/frontend
    ports:
      - 8000:8000
    networks:
      - doctor-app-1
    depends_on:
      - backend
    command: >
      sh -c "npm i -g --force yarn && yarn install && yarn start"

  backend:
    image: node:lts
    working_dir: /backend
    container_name: "Express-Backend"
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    networks:
      - doctor-app-1
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      NODE_ENV: development
      PORT: 3000
      MONGODB_CONNECTION_STRING: mongodb://mongo/doctor_app_v1
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 2
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 15
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 5
      SMTP_EMAIL_HOST: mailhog
      SMTP_EMAIL_PORT: 1025
      SMTP_EMAIL_USERNAME: 
      SMTP_EMAIL_PASSWORD:
      DEFAULT_EMAIL_FROM: no-reply@docjunction.com
      JWT_SECRET: u9n2_LxfpAQewpy7JzVU7yBxNBiW9n_NCFfLGlG43BSH6TOk5cl4ZtrkPg9rOKJ6Vlq8Kk_6N3npBq59dXcBAlb5rWyM3Rh9jrHBeaasnZMs2LiVrb-mFljIyYnPr10AeQEC7FjJupefrlE0YySC11AYBprsCt7HA3A3bhpwzDKmgatiAQtSahbeJiewmdyGNhFAYK5RHONqCmpR5TungCiyZCrnTg6aDInnBcrlNFLyHS_PaJG0pfUOBjDJny4GuqBDsYRo2VKwSGJO_CpnC

    command: >
      sh -c "npm i -g nodemon && npm install && nodemon ./bin/www"

  mongo:
    image: mongo
    container_name: "Mongo-DB"
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/mongo/data:/data/db
      - ./docker/data/mongo/mongodb_config:/data/configdb
    networks:
      - doctor-app-1

  mailhog:
    image: mailhog/mailhog
    container_name: "Mail-Server"
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - doctor-app-1

networks:
  doctor-app-1:
    external: false
  default:
    driver: doctor-app-1

volumes:
  mongodb: null
  mongodb_config: null
